FROM node:22-slim AS builder

RUN corepack enable && corepack prepare pnpm@9.12.3 --activate

WORKDIR /app

COPY docker-build/package-deps.txt /tmp/package-deps.txt
RUN apt-get update && \
    apt-get install -y $(xargs < /tmp/package-deps.txt) && \
    rm -rf /var/lib/apt/lists/*

COPY pnpm-workspace.yaml package.json pnpm-lock.yaml tsconfig.base.json ./
COPY core ./core
COPY server ./server

RUN pnpm install --filter core --frozen-lockfile && pnpm --filter @troublepainter/core build
RUN pnpm install --filter server --frozen-lockfile && pnpm --filter server build

FROM node:22-slim AS production
WORKDIR /app

COPY docker-build/package-deps.txt /tmp/package-deps.txt
RUN apt-get update && \
    apt-get install -y $(xargs < /tmp/package-deps.txt) && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/pnpm-workspace.yaml ./
COPY --from=builder /app/server/package.json ./server/package.json
COPY --from=builder /app/server/dist ./server/dist
COPY --from=builder /app/core/package.json ./core/package.json
COPY --from=builder /app/core/dist ./core/dist

RUN corepack enable && corepack prepare pnpm@9.12.3 --activate && pnpm install --prod --no-optional --filter '!@troublepainter/core'

WORKDIR /app/server

ENV NODE_ENV=production
ENV PORT=3000

EXPOSE 3000

CMD ["node", "dist/main.js"]